script: bash doc/justDoDocs.sh
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: doc/html
  on:
    branch: master

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz    
    
#language: generic # don't install any environment
#
#script: bash ./deploy.sh
#env:
#  global:
#  - ENCRYPTION_LABEL: "<.... encryption label from previous step ....>"
#  - COMMIT_AUTHOR_EMAIL: "you@example.com"
#
