### This should help not recompile everything always
### Commands are documented by a double # after the rule name

.PHONY: all configure clean install distclean update build error-report help




all: build ## (Default) Build the ANITA software without installing


help: ## Display this help message
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' Makefile.hidden_until_you_run_build_script | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'


clean: cmake-clean ## Delete all compiled components in build directory

install: cmake-install ## Install compiled components to ANITA_UTIL_INSTALL_DIR

### TODO add doxygen into CMakelists 
# doc: legacy-doc

build: build/Makefile
	@+make -C  ./build || make error-report


update: ## Update the components without compiling anything
	@./checkForAnitaBuildToolUpdate.sh && ./updateComponents.sh


configure: build/Makefile ## Edit the pre-defined configure flags in the CMakeLists.txt files
	@ccmake . build 

dir-locals: ## Links a .dir-locals.el file for emacs users running cmake-ide
	@echo "Linking .dir-locals.el for emacs users running cmake-ide"
	@ln -s .dir-locals.el.must-be-linked .dir-locals.el


cmake-install:
	@make -C ./build install


error-report:
	@./error-report.sh


build/Makefile:
	@rm -rf build  # 
	@mkdir -p build 
	@cd build && cmake ../ 


distclean: ## Remove build directory (run ./buildAnita.sh to re-compile)
	@echo "Removing cmake directory" 
	@rm -rf build 
	unlink cmake
	unlink Makefile 


cmake-clean: build/Makefile 
	@make -C ./build clean 

