
### This should help not recompile everything always
###




.PHONY: all configure clean install distclean update build 

all: build
clean: cmake-clean
install: cmake-install 


### TODO add doxygen into CMakelists 
doc: legacy-doc

build: build/Makefile 
	@+make -C  ./build

update: 
	./updateComponents.sh

configure: build/Makefile 
	@ccmake . build 

cmake-install: 
	@make -C ./build install 

build/Makefile: 
	@rm -rf build  # 
	@mkdir -p build 
	@cd build && cmake ../ 

distclean: 
	@echo "Removing cmake directory" 
	@rm -rf build 
	@rm -rf components
	unlink cmake
	unlink Makefile 

cmake-clean: build/Makefile 
	@make -C ./build clean 
